version: "3"

services:
  master:
    image: jenkins/jenkins:2.285-centos7
    container_name: "jenkins-master"
    ports:
      - "8080:8080"
      - "50000:50000"
    networks: 
      net:
        aliases:
          - "jenkins-master"
    volumes:
      - /var/jenkins_data/master:/var/jenkins_home
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins-agent:2.0
    container-name: "jenkins-agent"
    ports:
      - "2222:22"
    networks:
      net:
        aliases:
          - "jenkins-slave1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/jenkins_data/slave1:/var/jenkins_home

networks:
  net:
